In [2]:
import numpy as np

In [4]:
matrix = np.array(   [
    [1,2,3],
     [4,5,6,]
])

matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
# Basic operations

In [8]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
result = A+B
print(result)

[[ 6  8]
 [10 12]]


In [9]:
print(A-B)

[[-4 -4]
 [-4 -4]]


In [10]:
print(A*B)

[[ 5 12]
 [21 32]]


In [12]:
from numpy.linalg import det



In [13]:
determinant = det(A)
determinant

np.float64(-2.0000000000000004)

In [18]:
random_matrix = A
random_matrix


array([[1, 2],
       [3, 4]])

In [25]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])


In [46]:
col_sums = matrix.sum(axis=0)
col_sums

array([12, 15, 18])

In [41]:
col_mean = matrix.mean(axis=0)
col_mean

array([4., 5., 6.])

In [43]:
col_std = matrix.std(axis=0)
col_std

array([2.44948974, 2.44948974, 2.44948974])

In [45]:
col_var = matrix.var(axis=0)
col_var

array([6., 6., 6.])

In [49]:
col = matrix.T
col[0]

array([1, 4, 7])

In [50]:
col_div_std = col/col_std

In [51]:
col_div_std

array([[0.40824829, 1.63299316, 2.85773803],
       [0.81649658, 2.04124145, 3.26598632],
       [1.22474487, 2.44948974, 3.67423461]])