In [1]:
import numpy as np

In [2]:
vectors = [
    [1, 0, 0, 0],
    [0, 1, 0, 0],
    [0, 0, 1, 0],
    [0, 0, 0, 1]
]


In [12]:
 

def check_vector_space_and_independence(vectors):
    # Convert the list of vectors to a numpy array and transpose it
    vectors = np.array(vectors).T
    
    print(vectors)

    # Calculate the determinant of the matrix formed by the vectors
    det = np.linalg.det(vectors)

    # Calculate the rank of the matrix formed by the vectors
    rank = np.linalg.matrix_rank(vectors)

    # Check if the vectors form a vector space and if they are linearly dependent or independent
    if det == 0:
        print("Doesn’t form a vector space and are also linearly dependent")
    elif rank < vectors.shape[0]:  # rank is compared to the number of vectors (rows)
        print("Forms a vector space and are linearly dependent")
    else:
        print("Forms a vector space and are also linearly independent")


In [13]:
check_vector_space_and_independence(vectors)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
Forms a vector space and are also linearly independent
